---
- hosts: all
  become: true
  tasks:
    - name: install needed network manager libs
      package:
       name:
        - NetworkManager-glib
        - nm-connection-editor
        - libsemanage-python
        - policycoreutils-python
       state: present
    - name: configuring network
      nmcli:
       type: ethernet
       conn_name: eth0
       ifname: eth0
       ip4: 10.136.101.143/24
       gw4: 10.136.101.1
       dns4: 10.136.101.234
       dns4_search: got.com
       autoconnect: yes
       state: present
    - name: updating bootproto to static
      replace:
        path: /etc/sysconfig/network-scripts/ifcfg-eth0
        regexp: '^BOOTPROTO=dhcp'
        replace: 'BOOTPROTO=static' 
    - name: restart network service
      systemd:
        state: restarted
        daemon_reload: yes
        name: network
    - name: configuring hosts file
      blockinfile:
        dest: /etc/hosts
        block: |
         10.136.101.143 cl2.got.com cl2
    - name: setting the hostname
      command: hostnamectl set-hostname cl2.got.com
