---
- hosts: all
  become: true
  tasks:
    - name: install needed network manager libs
      package:
       name:
        - NetworkManager-glib
        - nm-connection-editor
        - libsemanage-python
        - policycoreutils-python
       state: present
    - name: configuring network
      nmcli:
       type: ethernet
       conn_name: "{{ IP_ETH }}"
       ifname: "{{ IP_ETH }}"
       ip4: "{{ IP_ADD_WITH_PREFIX }}"
       gw4: "{{ IP_GW }}"
       dns4: "{{ IP_DNS }}"
       dns4_search: "{{ IP_DOM }}"
       autoconnect: yes
       state: present
    - name: updating bootproto to static
      replace:
        path: /etc/sysconfig/network-scripts/ifcfg-{{ IP_ETH }}
        regexp: '^BOOTPROTO=dhcp'
        replace: 'BOOTPROTO=static' 
    - name: restart network service
      systemd:
        state: restarted
        daemon_reload: yes
        name: network
    - name: configuring hosts file
      blockinfile:
        dest: /etc/hosts
        block: |
         {{ IP_ADD }} {{ IP_CLIENT_FQDN }} {{ IP_CLIENT }}
    - name: setting the hostname
      command: hostnamectl set-hostname {{ IP_CLIENT_FQDN }}
